### ISSUE TITLE
npm install hexo-renderer-pug --save 执行失败了吗？

### ISSUE THREAD

**Issue by qingdujun** [BoizZ/hexo-theme-laughing#37]
macs-iMac-2:hexo mac$ pwd
/Users/mac/blog/hexo
macs-iMac-2:hexo mac$ npm install hexo-renderer-pug --save
npm WARN deprecated pug-loader@1.0.0: Please use pug-load for pug-loader@<=1.0.2.
hexo-renderer-pug@0.0.5
updated 1 package in 4.343s

> hexo clean
hexo g
hexo d

博文显示不了。

**Comment by qingdujun** [comment]
404

**Comment by qingdujun** [comment]
Error: Undefined variable: "$font-family".
ERROR Asset render failed: components/reset-css/sass/reset/mobile.css
Error: Undefined variable: "$font-family".
    at options.error (/Users/mac/NoteBook/node_modules/node-sass/lib/index.js:291:26)
Error: Undefined variable: "$font-family".
INFO  Generated: favicon.ico
ERROR Asset render failed: components/reset-css/sass/reset/basic.css
Error: Undefined variable: "$font-family".
    at options.error (/Users/mac/NoteBook/node_modules/node-sass/lib/index.js:291:26)
